[build]
  command = "npm run build:demo-v3 -- --output-path=dist/turismo-app"
  publish = "dist/turismo-app/browser"

[build.environment]
  NODE_VERSION = "20.20.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
